plugins {
    id 'maven-publish'
    id 'fabric-loom' version '1.8.13' apply false

    // https://github.com/ReplayMod/preprocessor
    // https://github.com/Fallen-Breath/preprocessor
    id 'com.replaymod.preprocess' version '9d21b334a7'
}

preprocess {
    strictExtraMappings = false

    def mc_1_21_1 = createNode('1.21.1', 1_21_01, '')
    def mc_1_21_3 = createNode('1.21.3', 1_21_03, '')
    def mc_1_21_4 = createNode('1.21.4', 1_21_04, '')

    mc_1_21_4.link(mc_1_21_3, null)
    mc_1_21_3.link(mc_1_21_1, null)
}

tasks.register('buildAndGather') {
    subprojects {
        dependsOn project.tasks.named('build').get()
    }
    doFirst {
        println 'Gathering builds'
        def buildLibs = {
            p -> p.buildDir.toPath().resolve('libs')
        }
        delete fileTree(buildLibs(rootProject)) {
            include '*'
        }
        subprojects {
            copy {
                from(buildLibs(project)) {
                    include '*.jar'
                    exclude '*-dev.jar', '*-sources.jar', '*-shadow.jar'
                }
                into buildLibs(rootProject)
                duplicatesStrategy DuplicatesStrategy.INCLUDE
            }
        }
    }
}
